[package]
name = "gen-schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = {path = "../config", features=["schemars"]}
schemars = "0.8.12"
serde_json = "1.0.105"