[workspace]
members = ["task-balancer", "secure-comms", "chatter-protocol", "config", "runner", "server", "gen-schema", "frontend", "plugin-manager", "alfred-plugin-api", "alfred-plugin"]
resolver = "2"