[workspace]
members = ["task-balancer", "secure-comms", "chatter-protocol", "config", "runner", "server", "gen-schema", "frontend", "plugin-manager", "gilbert-plugin-api", "gilbert-plugin"]
resolver = "2"